config/routes.rb
Checkm8::Application.routes.draw do
  root to:"home#index"
  resources :users
  resources :banks, :only => [:index, :new, :create, :show]
  resources :transactions, :only => [:new, :create]

  get "bank/graph" => 'banks#showgraph'
  get "bank/data/:id" => 'banks#data', :as => :data
  get 'transaction/form' => 'transactions#trans', :as => :trans
  post "/transaction/tc" => 'transactions#tc', :as => :tc

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/bank.rb
# == Schema Information
#
# Table name: banks
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Bank < ActiveRecord::Base
  attr_accessible :name
  def withdrawals
    Transaction.where(:from => self.name)
  end
  def deposits
    Transaction.where(:to => self.name)
  end

  # class method that displays all the names
  def self.all_names
    Bank.all.map(&:name).sort.uniq
  end

  def transactions(auth)
    k=[]
    if auth.nil?
      []
    else
        k = Transaction.where(:to => self.name).select! {|trans| trans.user_id = auth.id } || []
        #objects.sort_by {|obj| obj.attribute}
        k << Transaction.where(:from => self.name).select! {|trans| trans.user_id = auth.id }
        #Transaction.where(:from => self.name)
        k.flatten
    end
  end
  def sorted_trans(auth)
    if self.transactions(auth).first.present?
      self.transactions(auth).sort_by {|obj| obj.dt}
    else
      []
    end
  end
  def transactionrecord(auth)
    data =[]
    balance = 0
    self.sorted_trans(auth).each do |trans|
      change = (trans.from == self.name ? -trans.amount.to_f : trans.amount.to_f)
      data << { y: trans.dt, a: balance} #So that you get a point above
      data << { y: trans.dt, a: balance+=change } #get the change
    end
    data
  end

  def ubalance(auth)
    balance = 0
    self.sorted_trans(auth).each do |trans|
      change = (trans.from == self.name ? -trans.amount.to_f : trans.amount.to_f)
      balance += change
    end
    balance
  end
end

app/models/transaction.rb
# == Schema Information
#
# Table name: transactions
#
#  id         :integer          not null, primary key
#  amount     :decimal(, )
#  from       :string(255)
#  to         :string(255)
#  dt         :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Transaction < ActiveRecord::Base
  attr_accessible :amount, :from, :to,:user_id, :dt
  belongs_to :user
  validates :amount, :numericality => true
  validates :amount, :numericality => {:greater_than => 0}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_many :transactions
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authentication
  private
  def authentication
    @auth = (session[:user_id].present?) ? User.find(session[:user_id]) : nil
  end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  def show
    @transaction = Transaction.new
    @bank = Bank.find(params[:id])
  end
  def new
    @bank = Bank.new
  end
  def create
    bank = Bank.create(params[:bank])
    @banks = Bank.order(:name)
  end
  def showgraph
    render :json => Bank.first.transactionrecord(@auth)
  end
    def data
      @bank = Bank.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
  @banks = Bank.order(:name)
end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
    user = User.where(:email => params[:email]).first
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      @banks = Bank.order(:name)
    else
      session[:user_id] = nil
    end
    authentication
  end
  def destroy
    session[:user_id] = nil
    @auth = nil
    authentication
    redirect_to(root_path)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    @transaction= Transaction.new(user_id:30)
  end
  def create
    transaction = Transaction.create(params[:transaction])
    transaction.dt = Time.now
    transaction.save
  end
  def trans
    @trans= Transaction.new(user_id:30)#user_id:@auth.id)
  end
  def tc #nicks create
    t = Transaction.create(params[:transaction])
    t.dt = Time.now
    t.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_nav
    if @auth.present?
      "<li>#{link_to(@auth.name, '/login', :method => :delete, :class => 'button')}</li>"
    end
  end
end

app/views/banks/_data.html.haml
-if @bank.transactions(@auth).first.present?
  %table
    -@bank.transactions(@auth).each do |trans|
      %tr
        %td
          -if trans.from == @bank.name
            Withdrawl
          -else
            Deposit
        %td
          =trans.amount
        %td
          =trans.dt

app/views/banks/_form.html.haml
= form_for @bank, :remote => true do |f|
  %fieldset
    %legend
    = f.label :name, nil, :class => 'formtext'
    = f.text_field :name, :autofocus => true
    = link_to('Cancel', '#', :'data-clear-form' => true, :class => 'button tiny radius')
    = f.submit nil, :class => 'button tiny radius'

app/views/banks/_graph.html.haml
#graph
%script
  displaychart();

app/views/banks/create.js.erb
$('#form').empty();
$('#banks').empty().append('<%=j render :partial => 'home/banks' %>')

app/views/banks/data.js.erb
alert("Hello!");
$("#data").empty().append("<%=j render :partial => 'data'%>);

app/views/banks/new.js.erb
$("#trans_form").empty();
$('#form').empty().append('<%=j render :partial => 'form' %>')

app/views/banks/show.html.haml
=link_to("Data",data_path(@bank.id),:class=>'button radius tiny', :remote => true)
=link_to("Graph", "#",id:"graphit")

.row
  .small-12
    %h1= @bank.name


=link_to("New Transaction",trans_path,:class=>'button radius tiny', :remote => true)
#trans_form

= link_to('Transfer', new_transaction_path, :class=>'button radius tiny', :remote=>true)
#transaction_form

#main_show
  #data
    =render :partial => "data"
  #graph
    %script
      getchartdata();

app/views/banks/showgraph.js.erb
alert(<%=raw @info %>);
console.log((<%=raw @info %>));
//displaychart();

app/views/home/_banks.html.haml
- if @auth.present?
  %table
    %tr
      %th Bank
      %th Balance
    - @banks.each do |bank|
      %tr
        %td= link_to(bank.name, bank)
        %td= bank.ubalance(@auth)

app/views/home/_links.html.haml
- if @auth.nil?
  = link_to('New Account', new_user_path, :remote => true, :class => 'button large radius')
  = link_to('Login', login_path, :remote => true, :class => 'button large radius')
- else
  = link_to('Add Bank', new_bank_path, :remote => true, :class => 'button large radius')
  / = link_to(@auth.name, login_path, :remote => true, :method => :delete, :class => 'button large radius alert')

app/views/home/index.html.haml
#anonymous
#container
  .row
  .large-12.columns
    / %br
    / = link_to('New Account', new_user_path, :remote => true, :class => 'button large radius')
    / = link_to('Login', login_path, :remote => true, :class => 'button large radius')
#transaction_form
.row
  .large-12.columns
    #links
      = render :partial => 'links'
    #form
    #banks
      = render :partial => 'banks'


/ #anonymous
/ #container
/   .row
/   .large-12.columns
/     %br
/     = link_to('New Account', new_user_path, :remote => true, :class => 'button large radius')
/     = link_to('Login', login_path, :remote => true, :class => 'button large radius', 'data-reveal-id' => 'formid')
/ #transaction_form
/ .row
/   .large-12.columns
/     #links
/       / = render :partial => 'links'
/     #form
/     #banks
/       = render :partial => 'banks'

app/views/home/test.html.erb
 .reveal-modal{:class => "[medium]", :class => 'reveal-overlay', :id => 'formid'}
        = form_tag '/login', :remote => true do
          = label_tag :email
          = text_field_tag :email, nil, :autofocus => true
          = label_tag :password
          = password_field_tag :password
          = link_to('Cancel', '#', :'data-clear-form' => true, :class => 'button tiny radius')
          = submit_tag 'Log In', :class => 'button tiny radius'
      %a.close-reveal-modal ×

app/views/layouts/_body.html.erb
<div id="thumbs"></div>
<div class="row">
  <div class="large-12 columns">
    <%= yield %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="nav-bar right">
     <ul class="button-group">
       <li><%= link_to('Home', root_path, :class => 'button') %></li>
       <li><%= link_to('Contact Us', root_path, :class => 'button') %></li>
       <%== login_nav %>
      </ul>
    </div>
    <h2 class='subheader'>Checkm8</h2>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Checkm8</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='nav'><%= render :partial => 'layouts/nav' %></div>
  <div id='body'><%= render :partial => 'layouts/body' %></div>
  <div id='footer'><%= render :partial => 'layouts/footer' %></div>

  <script>
  $(document).foundation();
  </script>






</body>
</html>

app/views/session/_form.html.haml
.row
  .large-6.columns
    %fieldset
      %legend
      = form_tag '/login', :remote => true do
        = label_tag :email
        = text_field_tag :email, nil, :autofocus => true
        = label_tag :password
        = password_field_tag :password
        = link_to('Cancel', '#', :'data-clear-form' => true, :class => 'button tiny radius')
        = submit_tag 'Log In', :class => 'button tiny radius'
  .large-6.columns


  / .row
  / .large-6.columns
  /   #formid
  /     .reveal-modal{:class => "[medium]", :class => 'reveal-overlay', :id => 'formid'}
  /       = form_tag '/login', :remote => true do
  /         = label_tag :email
  /         = text_field_tag :email, nil, :autofocus => true
  /         = label_tag :password
  /         = password_field_tag :password
  /         = link_to('Cancel', '#', :'data-clear-form' => true, :class => 'button tiny radius')
  /         = submit_tag 'Log In', :class => 'button tiny radius'
  /     %a.close-reveal-modal ×
  / .large-6.columns

app/views/session/_logout_link.html.haml
%li
  = link_to(@auth.email, '/login', :method => :delete, :remote => true, :class => 'button tiny alert')

app/views/session/create.js.erb
<% if session[:user_id].present? %>
  $('#nav').empty().append('<%=j render(:partial => 'layouts/nav') %>')
  $('#banks').empty().append('<%=j render(:partial => 'home/links') %>')
  $('#form').empty()
  $('#banks').empty().append('<%=j render(:partial => 'home/banks') %>')
<% else %>
  $('#form').empty().append('<%=j render(:partial => 'form') %>')
<% end %>

app/views/session/destroy.js.erb
$('#nav').empty().append('<%=j render(:partial => 'layouts/nav') %>')
$('#bankd').empty().append('<%=j render :partial => 'home/banks') %>')
$('.email').remove();
show_or_hide_login_register_links();
$('#container').empty();

app/views/session/new.js.erb
$('#anonymous').hide();
$('#form').empty().append('<%=j render(:partial => 'form') %>');

app/views/transactions/_form.html.haml
= form_for @transaction, :remote=>true do |f|
  = f.hidden_field :user_id
  = f.label         :from
  = f.select        :from, options_for_select(Bank.all_names)
  = f.label         :to
  = f.select        :to, options_for_select(Bank.all_names)
  = f.label         :amount
  = f.text_field    :amount
  = button_to_function('Cancel', 'cancel_form()',:class => 'button radius tiny alert')
  = f.submit "Create Transaction", :class=>'button radius tiny'

app/views/transactions/_transform.html.haml
.row
  .large-3.columns
    = form_for @trans, :remote => true, :url => tc_path do |f|
      = f.hidden_field :user_id
      = f.label         :amount
      = f.text_field :amount
      = f.label         :from
      = f.text_field :from
      = f.label         :to
      = f.text_field :to
      = button_to_function('Cancel', 'cancel_trans()',:class => 'button radius tiny alert')
      = f.submit 'Apply Transaction', :id => 'create_user_button', :class => 'button radius tiny'
  .large-9.columns

app/views/transactions/create.js.erb
$('#transaction_form').empty();
$('#main_show').empty().append("<%=j render :partial=>'banks/graph' %>");

app/views/transactions/new.js.erb
$('#transaction_form').empty().append("<%=j render :partial=>'form'%>");

app/views/transactions/tc.js.erb
$('#trans_form').empty();
$('#data').empty();
getchartdata();

app/views/transactions/trans.js.erb
$('#trans_form').empty().append('<%=j render(:partial => 'transform') %>');

app/views/users/_form.html.haml
.row
  .large-6.columns
    %fieldset
      %legend
      = form_for @user, :url => users_path, :remote => true do |f|
        = f.label :email
        = f.text_field :email, :autofocus => true
        = f.label :name
        = f.text_field :name
        = f.label :password
        = f.password_field :password
        = f.label :password_confirmation
        = f.password_field :password_confirmation
        = link_to('Cancel', '#', :'data-clear-form' => true, :class => 'button tiny radius')
        = f.submit "Create Account", :class => 'button tiny radius'
  .large-6.columns

app/views/users/create.js.erb
<% if @user.valid? %>
  $('#form').empty().after('<p id=successfully>You have successfully created an account.</p>');
<% else %>
  $('#form').empty().append('<%=j render(:partial => 'form') %>');
<% end %>

app/views/users/new.js.erb
$('#form').empty().append('<%=j render(:partial => 'form') %>');